"use client";

import Link from "next/link";
import { CalendarPlus, Edit3, MapPin, Trash2 } from "lucide-react";
import { useState } from "react";
import { createEvent, deleteEvent, updateEvent } from "@/lib/api";
import type { EventItem } from "@/types/api";
import { ActionButton } from "@/components/ui/ActionButton";
import { GlassCard } from "@/components/ui/GlassCard";
import { Modal } from "@/components/ui/Modal";
import { Toast } from "@/components/ui/Toast";

export function EventsManager({ events }: { events: EventItem[] }) {
  const [list, setList] = useState(events); const [editing, setEditing] = useState<EventItem | null>(null); const [open, setOpen] = useState(false); const [toast, setToast] = useState<string | null>(null);
  const flash = (text: string) => { setToast(text); setTimeout(() => setToast(null), 2400); };
  async function save(form: FormData) { const payload = Object.fromEntries(form.entries()); const result = editing ? await updateEvent(editing.id, payload) : await createEvent(payload); if (!result.data) return flash(result.error ?? "Event save failed"); setList((current) => editing ? current.map((item) => item.id === result.data!.id ? result.data! : item) : [result.data!, ...current]); setOpen(false); flash("Event saved"); }
  async function remove(item: EventItem) { if (!window.confirm(`Delete ${item.name}?`)) return; await deleteEvent(item.id); setList((current) => current.filter((entry) => entry.id !== item.id)); }
  return <div className="space-y-5"><div className="flex justify-end"><ActionButton variant="primary" onClick={() => { setEditing(null); setOpen(true); }}><CalendarPlus size={16} /> New Event</ActionButton></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{list.map((item) => <GlassCard key={item.id} className="event-stage glow-card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-signal">{item.event_type ?? "DJ Event"}</p><h2 className="mt-2 text-xl font-semibold text-white">{item.name}</h2></div><strong className="rounded-xl bg-signal/12 px-2 py-1 text-sm text-signal">{item.readiness_percent}%</strong></div><p className="mt-3 text-sm text-white/58">{item.event_date ? new Date(item.event_date).toLocaleDateString() : "Date to be set"}</p><p className="mt-1 flex items-center gap-1 text-sm text-white/48"><MapPin size={14} /> {item.venue ?? "Venue to be set"}</p><div className="mt-5 flex gap-2"><Link href={`/events/${item.id}`}><ActionButton>Open plan</ActionButton></Link><ActionButton onClick={() => { setEditing(item); setOpen(true); }}><Edit3 size={15} /></ActionButton><ActionButton variant="danger" onClick={() => remove(item)}><Trash2 size={15} /></ActionButton></div></GlassCard>)}</div>{!list.length ? <GlassCard className="p-8 text-center text-white/55">Create your first event to plan timelines, prep checklists, and music links.</GlassCard> : null}<Modal open={open} title={editing ? "Edit Event" : "Create Event"} onClose={() => setOpen(false)}><form action={save} className="grid gap-3"><Input name="name" label="Event name" value={editing?.name} required /><Input name="event_type" label="Event type" value={editing?.event_type} /><Input name="event_date" label="Event date and time" type="datetime-local" value={editing?.event_date?.slice(0,16)} /><Input name="venue" label="Venue" value={editing?.venue} /><Input name="client_name" label="Client" value={editing?.client_name} /><Input name="expected_guests" label="Expected guests" type="number" value={editing?.expected_guests} /><Input name="mood" label="Mood" value={editing?.mood} /><textarea name="notes" defaultValue={editing?.notes ?? ""} placeholder="Notes" className="min-h-24 rounded-2xl border border-white/10 bg-white/8 p-3 text-white" /><div className="flex justify-end"><ActionButton type="submit" variant="primary">Save Event</ActionButton></div></form></Modal><Toast message={toast} /></div>;
}
function Input({ label, value, ...props }: Omit<React.InputHTMLAttributes<HTMLInputElement>, "value"> & { label: string; value?: string | number | null }) { return <label className="text-sm text-white/64">{label}<input {...props} defaultValue={value ?? ""} className="mt-1 h-10 w-full rounded-xl border border-white/10 bg-white/8 px-3 text-white" /></label>; }
