"use client";

import { ListMusic, Pause, Play, Repeat, Repeat1, Shuffle, SkipBack, SkipForward, Trash2, Volume2, X } from "lucide-react";
import { useState } from "react";

import { Badge } from "@/components/ui/Badge";
import { usePlayer } from "@/components/player/PlayerProvider";

function formatTime(value: number) { if (!Number.isFinite(value) || value < 0) return "0:00"; return `${Math.floor(value / 60)}:${Math.floor(value % 60).toString().padStart(2, "0")}`; }

export function MiniPlayer() {
  const [drawerOpen, setDrawerOpen] = useState(false);
  const { currentTrack, queue, recentlyPlayed, playing, status, errorMessage, currentTime, duration, volume, repeatMode, shuffle, togglePlay, previous, next, seek, setVolume, removeFromQueue, clearQueue, playFromQueue, cycleRepeat, toggleShuffle } = usePlayer();
  const hasTrack = Boolean(currentTrack);
  return (
    <div className="fixed inset-x-3 bottom-3 z-40 lg:left-[19rem] lg:right-5">
      {drawerOpen ? <div className="absolute bottom-[calc(100%+0.75rem)] right-0 w-full max-w-xl rounded-2xl border border-white/10 bg-deck-950/95 p-4 shadow-[0_24px_70px_rgba(0,0,0,0.46)] backdrop-blur-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-signal">Local queue</p><p className="mt-1 text-sm text-white/55">{queue.length} tracks · {recentlyPlayed.length} recently played</p></div><button onClick={() => setDrawerOpen(false)} className="grid size-9 place-items-center rounded-xl text-white/60 hover:bg-white/8"><X size={17} /></button></div><div className="mt-4 flex gap-2"><button onClick={cycleRepeat} className={`grid size-9 place-items-center rounded-xl ${repeatMode !== "off" ? "bg-signal/15 text-signal" : "text-white/58 hover:bg-white/8"}`} aria-label={`Repeat ${repeatMode}`}>{repeatMode === "one" ? <Repeat1 size={16} /> : <Repeat size={16} />}</button><button onClick={toggleShuffle} className={`grid size-9 place-items-center rounded-xl ${shuffle ? "bg-signal/15 text-signal" : "text-white/58 hover:bg-white/8"}`} aria-label="Toggle shuffle"><Shuffle size={16} /></button><button onClick={clearQueue} className="ml-auto inline-flex items-center gap-2 rounded-xl px-3 text-xs text-white/55 hover:bg-cue/10 hover:text-cue"><Trash2 size={14} /> Clear queue</button></div><div className="mt-4 max-h-52 space-y-2 overflow-y-auto soft-scrollbar">{queue.length ? queue.map((song) => <div key={song.id} className={`flex items-center gap-3 rounded-xl px-3 py-2 ${currentTrack?.id === song.id ? "bg-signal/10" : "bg-white/[0.035]"}`}><button onClick={() => playFromQueue(song)} className="min-w-0 flex-1 text-left"><p className="truncate text-sm font-medium text-white">{song.title}</p><p className="truncate text-xs text-white/48">{song.artist?.name ?? "Unknown artist"}</p></button><button onClick={() => removeFromQueue(song.id)} className="grid size-7 place-items-center rounded-lg text-white/45 hover:bg-cue/10 hover:text-cue" aria-label={`Remove ${song.title}`}><X size={14} /></button></div>) : <p className="rounded-xl border border-dashed border-white/10 p-3 text-sm text-white/48">Play a local track to build a queue.</p>}</div>{recentlyPlayed.length ? <div className="mt-4 border-t border-white/8 pt-3"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-white/42">Recently played</p><div className="mt-2 flex flex-wrap gap-2">{recentlyPlayed.slice(0, 5).map((song) => <button key={song.id} onClick={() => playFromQueue(song)} className="max-w-40 truncate rounded-lg bg-white/7 px-2 py-1 text-xs text-white/62 hover:bg-white/12">{song.title}</button>)}</div></div> : null}</div> : null}
      <div className="glass music-sheen flex min-h-16 items-center gap-3 rounded-2xl px-3 py-2 shadow-[0_18px_50px_rgba(0,0,0,0.35)] md:px-4"><div className="hidden size-10 shrink-0 rounded-xl bg-[radial-gradient(circle_at_70%_20%,rgba(240,106,166,0.82),transparent_25%),linear-gradient(135deg,#17123a,#082839)] sm:block" /><div className="min-w-0 w-36 shrink-0 md:w-52"><p className="truncate text-sm font-semibold text-white">{currentTrack?.title ?? "No local track selected"}</p><p className="truncate text-xs text-white/48">{errorMessage ?? currentTrack?.artist?.name ?? "Choose a local song to play"}</p></div><div className="hidden h-7 items-end gap-0.5 lg:flex" aria-hidden="true">{[35, 70, 50, 90, 42, 76, 58, 96, 48, 68, 38, 82].map((height, index) => <span key={index} className={`w-0.5 rounded-full bg-gradient-to-t from-signal to-cue ${playing ? "animate-pulse" : "opacity-55"}`} style={{ height: `${height}%`, animationDelay: `${index * 70}ms` }} />)}</div><div className="hidden min-w-0 flex-1 md:block"><input aria-label="Seek" type="range" min="0" max={duration || 0} step="0.1" value={Math.min(currentTime, duration || 0)} onChange={(event) => seek(Number(event.target.value))} disabled={!hasTrack || !duration} className="w-full accent-signal" /><div className="mt-1 flex justify-between text-[10px] text-white/42"><span>{formatTime(currentTime)}</span><span>{status === "loading" ? "Loading..." : formatTime(duration)}</span></div></div><div className="ml-auto flex items-center gap-1"><button onClick={previous} disabled={!hasTrack} className="grid size-8 place-items-center rounded-xl text-white/60 transition hover:bg-white/8 hover:text-white disabled:opacity-35" aria-label="Previous track"><SkipBack size={16} /></button><button onClick={togglePlay} disabled={!hasTrack} className="grid size-9 place-items-center rounded-xl bg-[linear-gradient(135deg,#58f0d1,#9b7cff)] text-deck-950 shadow-[0_0_20px_rgba(88,240,209,0.16)] disabled:opacity-35" aria-label={playing ? "Pause playback" : "Play track"}>{playing ? <Pause size={17} /> : <Play size={17} />}</button><button onClick={next} disabled={!hasTrack} className="grid size-8 place-items-center rounded-xl text-white/60 transition hover:bg-white/8 hover:text-white disabled:opacity-35" aria-label="Next track"><SkipForward size={16} /></button><button onClick={() => setDrawerOpen((value) => !value)} className={`grid size-8 place-items-center rounded-xl ${drawerOpen ? "bg-signal/15 text-signal" : "text-white/60 hover:bg-white/8"}`} aria-label="Open queue"><ListMusic size={16} /></button></div><div className="hidden items-center gap-2 lg:flex"><Volume2 size={15} className="text-white/48" /><input aria-label="Volume" type="range" min="0" max="1" step="0.05" value={volume} onChange={(event) => setVolume(Number(event.target.value))} className="w-16 accent-signal" /></div><Badge tone={status === "error" ? "cue" : hasTrack ? "signal" : "neutral"}>{status === "loading" ? "loading" : "local"}</Badge></div>
    </div>
  );
}
